#!/usr/bin/env bash
# Headless-provision a freshly-flashed Raspberry Pi OS card: enable SSH (key-only),
# join WiFi, create the user, set hostname/locale. Writes Raspberry Pi OS's
# `custom.toml` (processed on first boot) to the mounted boot partition.
#
# Usage:
#   sudo BOOT_MNT=/mnt/sdboot \
#        WIFI_SSID="YourWiFi" WIFI_PSK="YourPassword" \
#        PUBKEY="$(cat ~/.ssh/id_ed25519.pub)" \
#        ./provision-sd.sh
set -euo pipefail

BOOT_MNT="${BOOT_MNT:?set BOOT_MNT to the mounted boot partition (e.g. /mnt/sdboot)}"
HOSTNAME="${HOSTNAME_PI:-ceiling}"
USERNAME="${USERNAME:-pi}"
WIFI_SSID="${WIFI_SSID:?set WIFI_SSID}"
WIFI_PSK="${WIFI_PSK:?set WIFI_PSK}"
WIFI_COUNTRY="${WIFI_COUNTRY:-US}"
TIMEZONE="${TIMEZONE:-America/Los_Angeles}"
KEYMAP="${KEYMAP:-us}"
PUBKEY="${PUBKEY:?set PUBKEY to your SSH public key contents}"
# Console/sudo password for the user (SSH stays key-only). Random if unset.
USER_PASSWORD="${USER_PASSWORD:-$(openssl rand -base64 12)}"

if [ ! -d "$BOOT_MNT" ]; then
  echo "ERROR: $BOOT_MNT is not a directory / not mounted" >&2
  exit 1
fi

PW_HASH="$(openssl passwd -6 "$USER_PASSWORD")"

echo "==> Writing $BOOT_MNT/custom.toml"
cat > "$BOOT_MNT/custom.toml" <<EOF
# Generated by provision-sd.sh — Raspberry Pi OS first-boot customization.
config_version = 1

[system]
hostname = "$HOSTNAME"

[user]
name = "$USERNAME"
password = "$PW_HASH"
password_encrypted = true

[ssh]
enabled = true
password_authentication = false
authorized_keys = [
  "$PUBKEY"
]

[wlan]
ssid = "$WIFI_SSID"
password = "$WIFI_PSK"
password_encrypted = false
hidden = false
country = "$WIFI_COUNTRY"

[locale]
keymap = "$KEYMAP"
timezone = "$TIMEZONE"
EOF

# Belt-and-suspenders: a bare `ssh` file also enables sshd on every Pi OS release.
touch "$BOOT_MNT/ssh"

sync

echo
echo "Provisioned:"
echo "  hostname : $HOSTNAME  (try: ssh $USERNAME@$HOSTNAME.local)"
echo "  user     : $USERNAME"
echo "  wifi     : $WIFI_SSID ($WIFI_COUNTRY)"
echo "  ssh      : key-only (password auth disabled)"
echo
echo "  Console/sudo password (save this — needed for sudo on the Pi):"
echo "      $USER_PASSWORD"
echo
echo "Eject the card, boot the Pi, wait ~60-90s for first-boot setup, then SSH in."
